#!/usr/bin/env python3
"""Extract structured fact sheets from the country-entry HTML reports.

Level-1 knowledge layer: for every reports/**/*.html deck, emit a compact
facts/<batch-country>/<report>.md containing:
  - every T-numbered table, converted to markdown (metric rows keep their
    source/date/confidence text and [!] re-validate flags verbatim)
  - the exec "so what" blocks, the Reputation Bet, and section headings
so a single Claude Project / Cowork session can hold the whole 42-country
corpus at once and answer with report + table citations.

Run:  python3 tools/extract_facts.py        (from repo root)
Output is deterministic; re-run after every new report and commit facts/.
"""
import re, html as ihtml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "facts"

def strip_tags(s: str) -> str:
    s = re.sub(r"<[^>]+>", " ", s)
    s = ihtml.unescape(s)
    return re.sub(r"\s+", " ", s).strip()

def cell_text(cell: str) -> str:
    # keep the re-validate chip as a visible flag
    cell = re.sub(r'<span class="chip revalidate">\s*', " [!] ", cell)
    t = strip_tags(cell)
    return t.replace("|", "/")

def table_to_md(tbl: str) -> str:
    rows = re.findall(r"<tr[^>]*>(.*?)</tr>", tbl, flags=re.S)
    out, ncols = [], 0
    for i, row in enumerate(rows):
        cells = re.findall(r"<t[hd][^>]*>(.*?)</t[hd]>", row, flags=re.S)
        if not cells:
            continue
        vals = [cell_text(c) for c in cells]
        if i == 0:
            ncols = len(vals)
        out.append("| " + " | ".join(vals) + " |")
        if i == 0:
            out.append("|" + "---|" * ncols)
    return "\n".join(out)

def extract(path: Path) -> str:
    src = path.read_text(encoding="utf-8")
    body = re.sub(r"<style.*?</style>", "", src, flags=re.S)
    lines = [f"# FACTS — {path.stem}", f"_source file: {path.relative_to(ROOT)}_", ""]

    # walk the document in order: h2 headings, tcap captions, tables,
    # sowhat blocks, bet block
    pattern = re.compile(
        r'(<h2[^>]*>.*?</h2>)|(<div class="tcap">.*?</div>)|(<table.*?</table>)'
        r'|(<div class="sowhat">.*?</div>)|(<div class="bet">.*?</div>)'
        r'|(<div class="callout">.*?</div>)',
        flags=re.S,
    )
    for m in pattern.finditer(body):
        h2, tcap, tbl, sowhat, bet, callout = m.groups()
        if h2:
            lines += ["", "## " + strip_tags(h2), ""]
        elif callout:
            lines += ["**THE PLAY:** " + strip_tags(callout), ""]
        elif tcap:
            lines += ["### " + strip_tags(tcap)]
        elif tbl:
            lines += [table_to_md(tbl), ""]
        elif sowhat:
            lines += ["> SO WHAT: " + strip_tags(sowhat), ""]
        elif bet:
            lines += ["> **REPUTATION BET:** " + strip_tags(bet), ""]
    return "\n".join(lines) + "\n"

def main():
    index = ["# Fact-sheet index (auto-generated by tools/extract_facts.py)",
             "", "| Country folder | Report | Fact sheet | Words |", "|---|---|---|---|"]
    for hp in sorted(ROOT.glob("reports/*/*.html")) + sorted(ROOT.glob("benchmarks/*/*.html")):
        rel = hp.relative_to(ROOT)
        dest = OUT / rel.parent.name / (hp.stem + ".md")
        dest.parent.mkdir(parents=True, exist_ok=True)
        md = extract(hp)
        dest.write_text(md, encoding="utf-8")
        wc = len(md.split())
        index.append(f"| {rel.parent.name} | {hp.stem} | facts/{rel.parent.name}/{hp.stem}.md | {wc} |")
        print(f"{rel} -> {dest.relative_to(ROOT)} ({wc} words)")
    OUT.mkdir(exist_ok=True)
    (OUT / "INDEX.md").write_text("\n".join(index) + "\n", encoding="utf-8")

if __name__ == "__main__":
    main()
